import { afterEach, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/svelte";
import { photo, storage } from "./photo-test-fixtures.js";
import App from "./App.svelte";

afterEach(() => { cleanup(); history.replaceState(null, "", "/"); vi.unstubAllGlobals(); vi.restoreAllMocks(); });

it("retains photo state and previews across sidebar switches until lock", async () => {
  history.replaceState(null, "", "/photos#web_session=synthetic&web_upload_secret=proof");
  vi.stubGlobal("ResizeObserver", class { observe() {} disconnect() {} });
  vi.spyOn(HTMLElement.prototype, "clientWidth", "get").mockReturnValue(1000);
  vi.spyOn(HTMLElement.prototype, "clientHeight", "get").mockReturnValue(800);
  vi.stubGlobal("URL", class extends URL { static createObjectURL() { return "blob:synthetic"; } static revokeObjectURL() {} });
  const stored = storage();
  let pollFailed = false;
  let previewDenied = false;
  const fetcher = vi.fn(async (url: string) => {
    if (url.endsWith("/photos/hidden") && pollFailed) throw new Error("Temporary state failure");
    if (url.endsWith("/photos/hidden")) return new Response(JSON.stringify({ change_id: "initial", configured: true }));
    if (url.includes("/photos/assets/query")) return new Response(JSON.stringify({ items: [{ ...photo(1), previews: { ...photo(1).previews, grid: { state: "ready", generation_id: "synthetic" } } }], total: 1 }));
    if (url.includes("/previews/") && previewDenied) { previewDenied = false; return new Response(JSON.stringify({ detail: "Hidden photos are locked" }), { status: 403 }); }
    if (url.includes("/previews/")) return new Response("synthetic-jpeg");
    if (url.includes("/nodes/1")) return new Response(JSON.stringify({ id: 1, kind: "dir", name: "", revision: 1, path: "/" }));
    return new Response(JSON.stringify({ items: [], nodes: [], tags: [], profiles: [] }));
  });
  vi.stubGlobal("fetch", fetcher);
  render(App);
  await screen.findByRole("main", { name: "Photo library" });
  await fireEvent.click(await screen.findByRole("checkbox", { name: "Select photo Photo 1.jpg" }));
  const cacheName = stored.open.mock.calls[0][0];
  await waitFor(() => expect(stored.data.get(cacheName)?.size).toBe(1));
  const listings = () => fetcher.mock.calls.filter(([url]) => url.includes("/photos/assets/query")).length;
  const previews = () => fetcher.mock.calls.filter(([url]) => url.includes("/previews/")).length;
  expect(listings()).toBe(1);
  expect(previews()).toBe(1);
  const historyLength = history.length;
  await fireEvent.click(screen.getByRole("button", { name: "Photos" }));
  expect(history.length).toBe(historyLength);
  await fireEvent.click(screen.getByRole("button", { name: "Documents" }));
  expect(location.pathname).toBe("/");
  expect(screen.queryByRole("main", { name: "Photo library" })).toBeNull();
  await fireEvent.click(screen.getByRole("button", { name: "Photos" }));
  expect(location.pathname).toBe("/photos");
  await screen.findByText("1 selected photo");
  await screen.findByRole("checkbox", { name: "Select photo Photo 1.jpg" });
  expect(listings()).toBe(1);
  expect(previews()).toBe(1);
  const states = () => fetcher.mock.calls.filter(([url]) => url.endsWith("/photos/hidden")).length;
  await new Promise(resolve => setTimeout(resolve, 0));
  const beforeForeground = states();
  vi.spyOn(document, "visibilityState", "get").mockReturnValue("visible");
  await fireEvent(document, new Event("visibilitychange"));
  await waitFor(() => expect(states()).toBe(beforeForeground + 1));
  expect(listings()).toBe(1);
  await new Promise(resolve => setTimeout(resolve, 0));
  pollFailed = true;
  await fireEvent(document, new Event("visibilitychange"));
  await screen.findByRole("alert");
  expect(screen.getByRole("checkbox", { name: "Select photo Photo 1.jpg" })).not.toBeNull();
  expect(stored.data.get(cacheName)?.size).toBe(1);
  expect(listings()).toBe(1);
  pollFailed = false;
  await new Promise(resolve => setTimeout(resolve, 0));
  const recovered = vi.fn();
  window.addEventListener("docbank-photo-privacy", recovered, { once: true });
  await fireEvent(document, new Event("visibilitychange"));
  await waitFor(() => expect(recovered).toHaveBeenCalledOnce());
  await waitFor(() => expect(screen.queryByRole("alert")).toBeNull());
  await screen.findByRole("checkbox", { name: "Select photo Photo 1.jpg" });
  previewDenied = true;
  window.dispatchEvent(new Event("docbank-photo-privacy"));
  await waitFor(() => expect(previews()).toBeGreaterThan(2));
  expect(screen.getByRole("main", { name: "Photo library" })).not.toBeNull();
  await waitFor(() => expect(stored.data.has(cacheName)).toBe(false));
  history.replaceState(null, "", "/");
  await fireEvent(window, new PopStateEvent("popstate"));
  await waitFor(() => expect(screen.queryByRole("main", { name: "Photo library" })).toBeNull());
  await fireEvent.click(screen.getByRole("button", { name: /Lock/ }));
  await waitFor(() => expect(stored.data.has(cacheName)).toBe(false));
});
