import { mkdir } from "node:fs/promises";
import path from "node:path";
import { expect, test } from "@playwright/test";
import type { AttachmentIdentity } from "../src/attachments.js";
import type { SnapshotPage } from "../src/snapshots.js";

const screenshots = process.env.DOCBANK_ATTACHMENT_NAVIGATION_SCREENSHOT_DIR;
const browserURL = process.env.DOCBANK_DB24_BROWSER_URL;
test("DB24 actual attachment navigation preserves frozen authority", async ({ page }) => {
  test.skip(!screenshots || !browserURL, "requires the real-daemon Go fixture");
  test.setTimeout(300_000);
  page.setDefaultTimeout(30_000);
  const fixture = JSON.parse(process.env.DOCBANK_DB24_FIXTURE!) as {
    parent: AttachmentIdentity; child: AttachmentIdentity; nested: AttachmentIdentity; inside: AttachmentIdentity;
  };
  await mkdir(screenshots!, { recursive: true, mode: 0o700 });
  const url = new URL(browserURL!);
  const fragment = new URLSearchParams(url.hash.slice(1));
  fragment.set("query", JSON.stringify({ v: 1, text: "", syntax: "simple", mode: "lexical", filters: {}, sort: { field: "path", direction: "asc" } }));
  url.hash = fragment.toString();
  let queryPosts = 0;
  const tickets: Record<string, unknown>[] = [];
  page.on("request", (request) => {
    const pathname = new URL(request.url()).pathname;
    if (request.method() === "POST" && pathname === "/api/v1/workspace/queries") queryPosts++;
    if (request.method() === "POST" && pathname === "/api/daemon/web-download") tickets.push(request.postDataJSON() as Record<string, unknown>);
  });
  await page.addInitScript(() => localStorage.setItem("docbank-theme", "dark"));
  await page.goto(url.toString());
  const accepted = page.waitForResponse((response) => new URL(response.url()).pathname === "/api/v1/workspace/queries" && response.request().method() === "POST");
  await page.getByRole("region", { name: "Query editor" }).getByRole("button", { name: "Run query", exact: true }).click();
  const snapshot = await (await accepted).json() as SnapshotPage;
  const frozen = page.getByRole("region", { name: "Frozen query results" });
  await expect(frozen).toHaveAttribute("data-snapshot-id", snapshot.snapshot_id);
  await expect(frozen).toHaveAttribute("data-member-hash", snapshot.member_hash);
  await page.getByRole("button", { name: "Close query editor", exact: true }).click();
  const origin = page.locator(`tr[data-snapshot-node="${fixture.parent.node_id}"]`);
  await origin.getByRole("cell", { name: "/01-family.eml", exact: true }).click();
  await origin.getByRole("checkbox").check();
  const selected = await page.locator("tr[data-snapshot-node][aria-selected=true]").getAttribute("data-snapshot-node");
  const membership = await page.locator("tr[data-snapshot-node]").evaluateAll((rows) => rows.map((row) => row.getAttribute("data-snapshot-node")));
  const queryCount = queryPosts;
  const unchanged = async () => {
    expect(queryPosts).toBe(queryCount);
    await expect(frozen).toHaveAttribute("data-snapshot-id", snapshot.snapshot_id);
    await expect(frozen).toHaveAttribute("data-member-hash", snapshot.member_hash);
    expect(await page.locator("tr[data-snapshot-node]").evaluateAll((rows) => rows.map((row) => row.getAttribute("data-snapshot-node")))).toEqual(membership);
    await expect(origin.getByRole("checkbox")).toBeChecked();
    expect(await page.locator("tr[data-snapshot-node][aria-selected=true]").getAttribute("data-snapshot-node")).toBe(selected);
  };
  await page.getByRole("tab", { name: "Attachments", exact: true }).click();
  const outgoing = page.getByRole("region", { name: "Outgoing attachments" });
  await expect(outgoing.getByRole("listitem")).toHaveCount(50);
  await outgoing.getByRole("button", { name: "Load more attachments", exact: true }).click();
  await expect(outgoing.getByRole("listitem")).toHaveCount(52);
  await outgoing.getByRole("button", { name: "Check inventory for synthetic-family", exact: true }).click();
  await expect(outgoing.getByText("Publication inventory: complete", { exact: true })).toBeVisible();
  let release!: () => void;
  let reached!: () => void;
  const held = new Promise<void>((resolve) => { release = resolve; });
  const reachedVersion = new Promise<void>((resolve) => { reached = resolve; });
  const versionRoute = `**/api/v1/versions/${fixture.child.version_id}`;
  await page.route(versionRoute, async (route) => {
    reached();
    await held;
    await route.continue();
  }, { times: 1 });
  await outgoing.getByRole("button", { name: "Open attachment repeated.txt, part 1.2", exact: true }).click();
  await reachedVersion;
  const cancelled = page.waitForEvent("requestfailed", { predicate: (request) => new URL(request.url()).pathname === `/api/v1/versions/${fixture.child.version_id}` });
  await page.getByRole("tab", { name: "Preview", exact: true }).click();
  release();
  await cancelled;
  await expect(page.locator(`[data-source-version="${fixture.parent.version_id}"]`)).toBeVisible();
  await expect(page.locator(`[data-source-version="${fixture.child.version_id}"]`)).toHaveCount(0);
  await page.getByRole("tab", { name: "Attachments", exact: true }).click();
  await outgoing.getByRole("button", { name: "Open attachment repeated.txt, part 1.2", exact: true }).click();
  await expect(page.getByText("Pinned child edition, verified from its exact version.", { exact: true })).toBeVisible();
  await expect(page.getByText("SHA-256 verified", { exact: true })).toBeVisible();
  expect(tickets.at(-1)).toMatchObject({ node_id: fixture.child.node_id, version_id: fixture.child.version_id, blob_hash: fixture.child.sha256, size: fixture.child.size, purpose: "preview" });
  await expect(page.getByText("New live head must never replace the related historical edition.", { exact: true })).toHaveCount(0);
  await unchanged();
  // A tall real viewport keeps the fixed selection dock below the inspector
  // during element capture; no UI styles or API responses are substituted.
  await page.setViewportSize({ width: 1440, height: 1800 });
  await page.getByRole("button", { name: "Download verified original", exact: true }).scrollIntoViewIfNeeded();
  await page.locator(`[data-source-version="${fixture.child.version_id}"]`).screenshot({ path: path.join(screenshots!, "web-attachment-historical-child.png"), animations: "disabled" });
  await page.getByRole("tab", { name: "Attachments", exact: true }).click();
  await page.getByRole("region", { name: "Incoming parents" }).getByRole("button", { name: "Open parent of repeated.txt, part 1.2", exact: true }).click();
  await expect(page.locator(`[data-source-version="${fixture.parent.version_id}"]`)).toBeVisible();
  await outgoing.getByRole("button", { name: "Load more attachments", exact: true }).click();
  await outgoing.getByRole("button", { name: "Open attachment nested.eml, part 1.53", exact: true }).click();
  await expect(page.locator(`[data-source-version="${fixture.nested.version_id}"]`)).toBeVisible();
  await expect(page.getByRole("region", { name: "Incoming parents" }).getByRole("button", { name: "Open parent of nested.eml, part 1.53", exact: true })).toBeVisible();
  await outgoing.getByRole("button", { name: "Open attachment inside.txt, part 1.2", exact: true }).click();
  await expect(page.getByText("Exact nested attachment bytes.", { exact: true })).toBeVisible();
  expect(tickets.at(-1)).toMatchObject({ node_id: fixture.inside.node_id, version_id: fixture.inside.version_id, blob_hash: fixture.inside.sha256, size: fixture.inside.size, purpose: "preview" });
  await page.getByRole("button", { name: "Back to previous document", exact: true }).click();
  await expect(page.locator(`[data-source-version="${fixture.nested.version_id}"]`)).toBeVisible();
  await unchanged();
  await page.locator(`[data-source-version="${fixture.nested.version_id}"]`).screenshot({ path: path.join(screenshots!, "web-attachment-nested-family.png"), animations: "disabled" });
  await page.getByRole("button", { name: "Return to frozen document", exact: true }).click();
  await expect(origin).toBeFocused();
  await expect(page.locator(`[data-source-version="${fixture.parent.version_id}"]`)).toBeVisible();
  await unchanged();
  console.log(`DB24 proof: snapshot ${snapshot.snapshot_id}; member hash ${snapshot.member_hash}; query POSTs ${queryCount}; ${membership.length} visible frozen members unchanged; exact historical and nested bytes verified; origin focus restored.`);
});
